version: "3"
services:
  flask:
    container_name: python
    build: ./python-app
    environment:
      - FLASK_APP=wire_app.py
    ports:
      - 5000:5000
  
  golang:
    container_name: go
    build: ./api-builder
    restart: always
    ports:
     - 8080:8080

  # proxy:
  #   build: ./nginx
  #   restart: always
  #   ports:
  #     - 80:80