"""added column to Foil_Samples table

Revision ID: 1170444df7ff
Revises: f0b143cdb2aa
Create Date: 2021-11-28 15:00:05.141183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1170444df7ff'
down_revision = 'f0b143cdb2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foil_samples', sa.Column('nucleus_number', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foil_samples', 'nucleus_number')
    # ### end Alembic commands ###
