"""empty message

Revision ID: 2be56dc6f02f
Revises: 
Create Date: 2021-11-27 21:40:05.221045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be56dc6f02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('irradiation_finished', sa.DateTime(), nullable=True),
    sa.Column('irradiation_time', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('foil_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('cooling_finished', sa.DateTime(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('cooling_time', sa.Float(), nullable=True),
    sa.Column('measuring_time', sa.Float(), nullable=True),
    sa.Column('reaction_rate', sa.Float(), nullable=True),
    sa.Column('cadmium_filter', sa.Boolean(), nullable=True),
    sa.Column('exp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exp_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    op.drop_table('experiments')
    # ### end Alembic commands ###
