"""empty message

Revision ID: 7a03f9004bd5
Revises: 
Create Date: 2021-11-21 18:03:21.257305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a03f9004bd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foils_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nuclide', sa.String(length=100), nullable=False),
    sa.Column('cross_section', sa.Float(), nullable=False),
    sa.Column('abundance', sa.Float(), nullable=False),
    sa.Column('half_life', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('resonance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nuclide')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foils_store')
    # ### end Alembic commands ###
