"""empty message

Revision ID: 1c9f2b8f745d
Revises: 
Create Date: 2021-11-09 17:55:08.252200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9f2b8f745d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('irradiation_time', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooling_time', sa.Float(), nullable=True),
    sa.Column('measuring_time', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.Column('exper_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['exper_name'], ['experiment.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    op.drop_table('experiment')
    # ### end Alembic commands ###
