"""empty message

Revision ID: 366065574bbf
Revises: 64c3fa444ab8
Create Date: 2021-11-15 22:02:11.235612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366065574bbf'
down_revision = '64c3fa444ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gormtests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gormtests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), server_default=sa.text("'newTestInsert'::text"), autoincrement=False, nullable=True),
    sa.Column('age', sa.BIGINT(), server_default=sa.text('22'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gormtests_pkey')
    )
    # ### end Alembic commands ###
