"""empty message

Revision ID: cd4c60d9efd3
Revises: 
Create Date: 2021-11-22 15:42:20.846463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4c60d9efd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foils_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nuclide', sa.String(length=100), nullable=False),
    sa.Column('cross_section', sa.Float(), nullable=False),
    sa.Column('abundance', sa.Float(), nullable=False),
    sa.Column('half_life', sa.Float(), nullable=False),
    sa.Column('energy', sa.String(length=150), nullable=False),
    sa.Column('release', sa.String(length=150), nullable=False),
    sa.Column('resonance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nuclide')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foils_store')
    # ### end Alembic commands ###
