"""added new table

Revision ID: f2f7cb635641
Revises: cd4c60d9efd3
Create Date: 2021-11-27 23:10:07.656015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f7cb635641'
down_revision = 'cd4c60d9efd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foil_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nucleus_number', sa.Float(), nullable=False),
    sa.Column('foil_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['foil_type'], ['foils_store.nuclide'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foil_data')
    # ### end Alembic commands ###
